name: church_members_events
description: Chuch Members & Events.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1
  
environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  async_loader: ^0.1.1
  json_annotation: ^1.2.0
  flutter_pagewise: ^0.5.0
  intl: ^0.15.7
  # http request helper
  dio: ^1.0.6
  image_picker: ^0.4.10
  modal_progress_hud: ^0.1.1
  shared_preferences: ^0.4.3
 
  
 
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 0.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^1.4.0
  # source_gen: ^0.9.1+1
  build_runner: ^1.0.0
  # app icon
  flutter_launcher_icons: ^0.6.1
flutter_icons:
  android: true 
  #ios: "Example-Icon"
  image_path: "assets/appicons/church.png"
  image_path_android: "assets/appicons/church.png"
  image_path_ios: "assets/appicons/church.png"
#  adaptive_icon_background: "#FFFAFAFA"
#  adaptive_icon_foreground: "assets/icon/icon-foreground.png"
# Run the command to generate the app icons:
# flutter pub get
# flutter pub pub run flutter_launcher_icons:main

  # async_loader: ^0.1.1

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - no-wifi.png
   - family.jpg
   - person.jpg
   - logo.png
   - rotator.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

